### ISSUE TITLE
Allow manually specifying connection URL.

### ISSUE THREAD

**Issue by adam-spurgeon-tp** [ansible-collections/community.elastic#108]
##### SUMMARY

Allow specifying the connection URL to be used for the login hosts.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

elastic_common

##### ADDITIONAL INFORMATION

If a connection path or fragments are needed to connect to an Elastic server, there is currently no way to specify them. This change would allow the manual specification for these cases.

```yaml
---
- name: Manage indices
  hosts: all
  connection: local
  module_defaults:
    community.elastic.elastic_index:
      auth_method: http_auth
      login_hosts:
        - https://elk.example.com:443/elastic
      login_password: "{{ elastic_password }}"
      login_user: "{{ elastic_user }}"
  tasks:
    - name: Test index
      community.elastic.elastic_index:
        state: present
        name: test-index-00001
        settings:
          index:
            lifecycle:
              name: 30d
              rollover_alias: test-index-current

```
