### ISSUE TITLE
Setting connection_options is not working

### ISSUE THREAD

**Issue by timhovius** [ansible-collections/community.elastic#113]
##### SUMMARY
When I try to set `connection_options`, I got an error:

`Elastic error: __init__() takes from 1 to 2 positional arguments but 3 positional arguments (and 2 keyword-only arguments) were given`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
All modules

##### ANSIBLE VERSION

```paste below
ansible [core 2.16.14]
  config file = None
  configured module search path = ['/home/tim/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/pipx/venvs/ansible/lib/python3.10/site-packages/ansible
  ansible collection location = /home/tim/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.12 (main, Jan 17 2025, 14:35:34) [GCC 11.4.0] (/opt/pipx/venvs/ansible/bin/python)
  jinja version = 3.1.5
  libyaml = True
```

##### COLLECTION VERSION
1.2.1

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
- name: Disable Elasticsearch shared allocation
  community.elastic.elastic_cluster_settings:
    auth_method: http_auth
    auth_scheme: https
    connection_options:
      - verify_certs: false
    login_hosts: "{{ inventory_hostname }}"
    login_user: user
    login_password: "{{ elasticsearch_password }}"
    settings: 
      cluster.routing.allocation.enable: primaries

```

##### ACTUAL RESULTS

```paste below
The full traceback is:
  File "/tmp/ansible_community.elastic.elastic_cluster_settings_payload__3620ex_/ansible_community.elastic.elastic_cluster_settings_payload.zip/ansible_collections/community/elastic/plugins/modules/elastic_cluster_settings.py", line 115, in main
  File "/tmp/ansible_community.elastic.elastic_cluster_settings_payload__3620ex_/ansible_community.elastic.elastic_cluster_settings_payload.zip/ansible_collections/community/elastic/plugins/module_utils/elastic_common.py", line 107, in connect
    **auth)
fatal: [es02]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "api_key_encoded": null,
            "auth_method": "http_auth",
            "auth_scheme": "https",
            "cafile": null,
            "connection_options": [
                {
                    "verify_certs": false
                }
            ],
            "login_hosts": [
                "es02"
            ],
            "login_password": "",
            "login_port": 9200,
            "login_user": "user",
            "persistent": true,
            "settings": {
                "cluster.routing.allocation.enable": "primaries"
            },
            "timeout": 30
        }
    },
    "msg": "Elastic error: __init__() takes from 1 to 2 positional arguments but 3 positional arguments (and 2 keyword-only arguments) were given"
}
```
